---
# Need to always return true because it always return error code if
# domain already issued
- name: Issue certificates (maybe need to wait for 30 seconds)
  shell: >
    {{ le_acme_command }} --issue --{{ item.method }} {{ item.dns | default('') }} --dnssleep 30
    -d {{ item.domain }}
  environment:
    CF_Token: "{{ item.cf_token | default('') }}"
    CF_Account_ID: "{{ item.cf_account_id | default('') }}"
    CF_Zone_ID: "{{ item.cf_zone_id | default('') }}"
    CF_Key: "{{ item.cf_key | default('') }}"
    CF_Email: "{{ item.cf_email | default('') }}"
  with_items: "{{ le_domains }}"
  register: le_issue_cmd
  failed_when: le_issue_cmd.rc != 0 and le_issue_cmd.rc != 2

- name: Create certificate key directory
  file:
    path: "{{ item.key_path | dirname }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  when:
    - item.key_path is defined
  with_items: "{{ le_domains }}"

- name: Create certificate fullchain directory
  file:
    path: "{{ item.fullchain_path | dirname }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  when:
    - item.fullchain_path is defined
  with_items: "{{ le_domains }}"

- name: Install the issued certificates
  command: >
    {{ le_acme_command }} --install-cert -d {{ item.domain }}
    --key-file {{ item.key_path }}
    --fullchain-file {{ item.fullchain_path }}
  when:
    - item.key_path is defined
    - item.fullchain_path is defined
  with_items: "{{ le_domains }}"

- name: Change permission of installed issued certificates
  file:
    path: "{{ item.key_path }}"
    mode: "{{ item.key_chmod }}"
  when:
    - item.key_chmod is defined
    - item.key_path is defined
  with_items: "{{ le_domains }}"
